FROM openjdk:17-alpine
COPY /target/scenario-processor-0.0.1-SNAPSHOT-jar-with-dependencies.jar /home/scenario-processor-0.0.1-SNAPSHOT-jar-with-dependencies.jar
EXPOSE 9010
CMD ["java","-jar","/home/scenario-processor-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]