pipeline {
    agent { docker { image 'maven:3.9.0-eclipse-temurin-11' } }
    stages {
        stage('build') {
            steps {
                sh 'cd ./test-scenario-parser-app/scenario-processor'
                sh 'mvn clean install -DskipTests=true'
            }
        }
    }
}