pipeline {
    agent { docker { image 'maven:3.9.0-eclipse-temurin-11' } }
    stages {
        stage('build') {
            steps {
                sh "rm -rf *"
                checkout scm
                sh "rm -rf !(./test-scenario-parser-app/scenario-processor/.)"
                sh "cp -a ./test-scenario-parser-app/scenario-processor/. ."
                sh "rm -rf ./test-scenario-parser-app/scenario-processor/."
                sh "mvn clean compile -DskipTests=true"
            }
        }
    }
}