server:
  port: 9020

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
    log-spans: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
  application:
    name: scenario-processor
  datasource:
    url: jdbc:postgresql://localhost:5432/scenario_configurator
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/scenario_configurator
    user: postgres
    password: postgres
    locations: classpath:/migrations
    sql-migration-prefix: V
    sql-migration-separator: "_"

processor:
  url: http://localhost:9010