server:
  port: 9020

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger:14268/api/traces
    log-spans: true

spring:
  application:
    name: scenario-processor
  datasource:
    url: jdbc:postgresql://postgres:5432/scenario_configurator
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://postgres:5432/scenario_configurator
    user: postgres
    password: postgres
    locations: classpath:/migrations
    sql-migration-prefix: V
    sql-migration-separator: "_"

processor:
  url: http://scenario-processor:9010