server:
  port: 9020

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 5775
    const-sampler:
      decision: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
      properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: scenario-configurator
  datasource:
    url: jdbc:postgresql://localhost:5433/scenario_configurator
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5433/scenario_configurator
    user: postgres
    password: postgres
    locations: classpath:/migrations
    sql-migration-prefix: V
    sql-migration-separator: "_"

processor:
  url: http://localhost:9010
