version: "3.9"
services:
  #configurator:
  #  image: kruchon/test-scenario-configurator:0.0.1
  #  ports:
  #    - "9020:9020"
  #processor:
  #  image: kruchon/test-scenario-processor:0.0.1
  #  ports:
  #    - "9010:9010"
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: "scenario_configurator"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"