FROM openjdk:17-alpine
COPY /target/scenario-configurator-0.0.1-SNAPSHOT-jar-with-dependencies.jar /home/scenario-configurator-0.0.1-SNAPSHOT-jar-with-dependencies.jar
EXPOSE 9020
CMD ["java","-jar","/home/scenario-configurator-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]